import * as vscode from "vscode";
import { getRecentCommits } from "./git";
import { CommitEntry } from "./types";

function renderCommitBlock(commit: CommitEntry): string {
  const fileList = commit.files.length
    ? commit.files.map((file) => `  - \`${file.path}\``).join("\n")
    : "  - No file list available";

  return [
    `### ${commit.subject}`,
    `- Commit: \`${commit.shortHash}\``,
    `- Author: ${commit.author}`,
    `- Date: ${commit.date}`,
    `- Stats: ${commit.stats.filesChanged} files changed, +${commit.stats.insertions} / -${commit.stats.deletions}`,
    "- Files:",
    fileList,
    ""
  ].join("\n");
}

export async function generateWorkspaceChangelog(workspaceFolder: vscode.WorkspaceFolder): Promise<string> {
  const configuration = vscode.workspace.getConfiguration("codeChronicle", workspaceFolder);
  const changelogFile = configuration.get<string>("changelogFile", "WORKSPACE_CHANGELOG.md");
  const maxCommits = configuration.get<number>("maxCommits", 12);
  const commits = await getRecentCommits(workspaceFolder, maxCommits);
  const targetUri = vscode.Uri.joinPath(workspaceFolder.uri, changelogFile);

  const header = [
    "# Workspace Changelog",
    "",
    `Generated by Code Chronicle on ${new Date().toLocaleString()}`,
    ""
  ].join("\n");

  const body = commits.map(renderCommitBlock).join("\n");
  const content = `${header}${body}`;

  await vscode.workspace.fs.writeFile(targetUri, Buffer.from(content, "utf8"));

  return targetUri.fsPath;
}

export function buildLatestCommitSummary(commit: CommitEntry): string {
  const touchedFiles = commit.files.slice(0, 5).map((file) => file.path).join(", ");
  const overflow = commit.files.length > 5 ? ` and ${commit.files.length - 5} more` : "";

  return [
    `${commit.subject} (${commit.shortHash})`,
    `Author: ${commit.author} on ${commit.date}`,
    `Changed ${commit.stats.filesChanged} files, +${commit.stats.insertions} / -${commit.stats.deletions}`,
    touchedFiles ? `Files: ${touchedFiles}${overflow}` : "Files: unavailable"
  ].join("\n");
}
